version: '3'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: simple
      MYSQL_DATABASE: simple
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init/:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  application:
    container_name: application
    build: ../
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database